name: 'Support question ❔'
description: I can't find a solution to my problem with MUI Design kit.
title: "[question] "
labels: ['status: waiting for maintainer', 'support: question']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        ⚠️ **Don't use this form if the problem is [a bug](https://github.com/mui/mui-design-kits/issues/new?assignees=&labels=status%3A+needs+triage&template=1.bug.yml) or a [feature request](https://github.com/mui/mui-design-kits/issues/new?assignees=&labels=status%3A+needs+triage&template=2.feature.yml), use the dedicated form instead.**
  - type: input
    attributes:
      label: Search keywords
      description: |
        Your issue may have already been reported! First search for duplicates among the [existing issues](https://github.com/mui/mui-design-kits/issues).
        If your issue isn't a duplicate, great! Please list the keywords you used so people in the future can find this one more easily:
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: The problem in depth
  - type: textarea
    attributes:
      label: Your environment
      description: The version of the design file you are using. The version is usually disabled in the footer of the design frames.
